version: '3.8'

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

